### ISSUE TITLE
multiple definition of `volk_fec_32f_s32f_normalize_a_orc_impl`

### ISSUE THREAD

**Issue by gsongsong** [SpectreJan/volk_fec#2]
In `orc/` directory, there are two ORC files for `volk_fec_32f_s32f_normalize_a_orc_impl`:
- `volk_fec_32f_s32f_norm.orc`
- `volk_fec_32f_s32f_normalize.orc`

And `lib/CMakeLists.txt` includes both:

```
#setup orc functions
file(GLOB orc_files ${CMAKE_SOURCE_DIR}/orc/*.orc)
foreach(orc_file ${orc_files})
```

Thus I get:

```
CMakeFiles/volk_fec.dir/volk_fec_32f_s32f_norm.c.o: In function `volk_fec_32f_s32f_normalize_a_orc_impl':
volk_fec_32f_s32f_norm.c:(.text+0x280): multiple definition of `volk_fec_32f_s32f_normalize_a_orc_impl'
CMakeFiles/volk_fec.dir/volk_fec_32f_s32f_normalize.c.o:volk_fec_32f_s32f_normalize.c:(.text+0x280): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libvolk_fec.so.0.0.0] Error 1
make[1]: *** [lib/CMakeFiles/volk_fec.dir/all] Error 2
make: *** [all] Error 2
```

I've succeeded installation with workaround renaming `volk_fec_32f_s32f_normalize.orc` with `volk_fec_32f_s32f_normalize.no-orc`. But I haven't tested it yet whether it runs okay or not.

commit hash is aca44d5b4b3d711bc6957dfefdf188651c65eec8

**Comment by SpectreJan** [comment]
Hi,
to be honest, I don't have a clue why I added the orc stuff. I remember that I had some problem with ORC on my machine and used some stupid hacks to make it work. But this was over a year ago and I havent touched nor looked at the code ever since. So I would have to go check whether it builds on my machine or not. But thanks for pointing it out.

Cheers and happy hacking,
Jan

**Comment by SpectreJan** [comment]
Yeah, I just had a look and somethings whack. One of the functions has the wrong name and I am not sure why. I am sure that I never manually wrote theese .orc files so maybe they were generated or the coding spirits wrote them. So renaming the *normalize* function in *norm*.orc to *norm* should fix the multiple definitions problem. Hope that helps. And thanks again for pointing that out. Nothing worse than repo branches that do not build!

Cheers and happy hacking,
Jan
